### ISSUE TITLE
Separate error type for schema change error

### ISSUE THREAD

**Issue by fushinari** [goodmami/wn#106]
If a separate error type or exception type was given for the schema change, we could easily do a try-catch based on the exception rather than on the more general wn.Error exception.

**Comment by goodmami** [comment]
That's a great idea. Like a `wn.SchemaError` or something. I'll do that, maybe even as a patch release.

Also, FWIW, this release is a very big change because I tried to implement all foreseeable schema changes in one release, even those for features that aren't implemented yet (#17, #105). Also, things like adding new relation types no longer require schema changes. The hope is that I won't need to change the schema again for a while.

**Comment by goodmami** [comment]
I'll merge #107 in a day or so if there are no objections.

**Comment by fushinari** [comment]
Thank you for addressing this so quickly! (Had exams, so I couldn't reply as soon as I wanted to)
