### ISSUE TITLE
No examples in pwn 3.1?

### ISSUE THREAD

**Issue by rudaoshi** [goodmami/wn#109]
Hi, I'm new to wordnet and your excellent wn project. 

I cannot find  any example in pwn 3.1, using following code:

```python 
len([s for x in wn.senses() if x.examples() ])
```

the code output 0.

**Comment by goodmami** [comment]
The problem is that the PWN data have the definition and examples combined. This is because the original WNDB format had them both combined into a "gloss" field.

```pycon
>>> import wn
>>> pwn = wn.Wordnet(lexicon='pwn:3.1')
>>> pwn.synsets('systemic')[0].definition()
'affecting an entire system; "a systemic poison"'
>>> pwn.synsets('systemic')[0].examples()
[]
```

 The English WordNet (an actively-developed fork of PWN), in contrast, stores them already split:

```pycon
>>> ewn = wn.Wordnet(lexicon='ewn:2020')
>>> ewn.synsets('systemic')[0].definition()
'affecting an entire system'
>>> ewn.synsets('systemic')[0].examples()
['"a systemic poison"']
```

The [omw-data](https://github.com/bond-lab/omw-data/) project maintains both the Open Multilingual Wordnet lexicons and the WN-LMF exports of the PWN. There's a plan to update the PWN files somewhat soon, and I've now [commented](https://github.com/bond-lab/omw-data/issues/3#issuecomment-809062537) that we should perhaps make this change for PWN, too.

Secondly, you're looking for examples on senses. I'd agree that this is the intuitive place to look for examples, because you want an example of a particular word for some concept, but currently the data doesn't have any examples on senses. You should look at the synsets instead:

```pycon
>>> len([x for x in ewn.senses() if x.examples()])
0
>>> len([x for x in ewn.synsets() if x.examples()])
34237
```

**Comment by rudaoshi** [comment]
Thank you very much for your help!

I've read the paper about the English WordNet and decided to use it insted of pwn.

And also, I will use synsets to find examples.
