### ISSUE TITLE
Improve wn.ic documentation and error messages regarding unsmoothed frequencies

### ISSUE THREAD

**Issue by M49ICKPIxi3** [goodmami/wn#137]
While trying to create a list of similarities between synsets I'm running lin similarity on each element of a list, so basically:
```python
first_word = wn.synsets(token.text, pos=wordnet_pos)[0]
hyponyms_ic = [(hyponym, lin(first_word, hyponym, wn_ic)) for hyponym in first_word.hyponyms()]
```
This throws a ValueError in the ic.py file line 32 (as of right now):
```python
return -log(synset_probability(synset, freq))
```

**Comment by goodmami** [comment]
Thanks for the report! If it's a ValueError, most likely `synset_probability(...)` is returning 0, which might be the case of an unseen word when `wn_ic` is created without smoothing. Can you share how you've created `wn_ic`?

Also I note that you're using `wn.synsets()` instead of querying a [Wordnet object](https://wn.readthedocs.io/en/latest/api/wn.html#the-wordnet-class). Using `wn.synsets()` may return results from a lexicon you didn't intend, as it searches any installed lexicon for the word. Therefore, if you've loaded `wn_ic` for some lexicon then query it with synsets from another lexicon, the count will be 0 even if `wn_ic` was created with smoothing. In this case, the following may work better:

```python
import wn, wn.ic
from wn.similarity import lin

pwn = wn.Wordnet('pwn:3.0')
path = '~/nltk_data/corpora/wordnet_ic/ic-brown.dat'
wn_ic = wn.ic.load(path, pwn)
...
first_word = pwn.synsets(token.text, pos=wordnet_pos)[0]
hyponyms_ic = [(hyponym, lin(first_word, hyponym, wn_ic)) for hyponym in first_word.hyponyms()]
```

**Comment by M49ICKPIxi3** [comment]
I apologize, I actually just abbreviated it. I instantiated a class that I'm using as a pipeline for Spacy, I didn't want to paste a whole class but I'm using the wordnet object itself, this is how it's being created.
```python
self.__wn = Wordnet(lexicon='pwn:3.0', lang=lang, lemmatizer=Morphy())
self.__ic = wn.ic.load('~/nltk_data/corpora/wordnet_ic/ic-brown.dat', self.__wn)
```
Also the word that led to the error was the verb 'crossed', if that helps with debugging

**Comment by goodmami** [comment]
Ok thanks, that helps. In this case it's because the `ic-brown.dat` file is created without any smoothing:

```python
>>> import wn, wn.ic
>>> from wn.similarity import lin
>>> from wn.morphy import Morphy
>>> pwn = wn.Wordnet('pwn:3.0', lemmatizer=Morphy())  # no need to set lang when lexicon is given
>>> ic = wn.ic.load('~/nltk_data/corpora/wordnet_ic/ic-brown.dat', pwn)
>>> first_word = pwn.synsets('crossed', pos='v')[0]
>>> first_word.hyponyms()
[Synset('pwn-01429825-v')]
>>> ic['v'][first_word.id]
139.0
>>> ic['v'][first_word.hyponyms()[0].id]
0.0
>>> lin(first_word, first_word.hyponyms()[0], ic)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/goodmami/postdoc/wn/wn/similarity.py", line 211, in lin
    ic2 = information_content(synset2, ic)
  File "/home/goodmami/postdoc/wn/wn/ic.py", line 32, in information_content
    return -log(synset_probability(synset, freq))
ValueError: math domain error
```

You can try using an IC file with `-add1` smoothing (or `-resnik-add1` if you prefer):

```python
>>> ic = wn.ic.load('~/nltk_data/corpora/wordnet_ic/ic-brown-add1.dat', pwn)
>>> ic['v'][first_word.id]
141.0
>>> ic['v'][first_word.hyponyms()[0].id]
1.0
>>> lin(first_word, first_word.hyponyms()[0], ic)
0.7978561602190527
```

I don't think this situation is a bug in Wn, but it could be improved with better documentation and/or better error messages. Any suggestions?

**Comment by M49ICKPIxi3** [comment]
Is there any disadvantages for using an IC file with the `-add1` smoothing? If not, then perhaps the documentation could default to using `ic = wn.ic.load('~/nltk_data/corpora/wordnet_ic/ic-brown-add1.dat', pwn)` instead of the IC file without smoothing. There could even be a sentence in the "Information Content-based Metric" section mentioning that.

Either that or maybe an Exception for the ic.py code which explains why the ValueError was thrown and what can be done about it. Hope that helps!

**Comment by goodmami** [comment]
> Is there any disadvantages for using an IC file with the -add1 smoothing?

I don't think so. It prevents these kind of divide-by-zero and other math domain errors, and I don't think anyone cares about the actual frequencies of the words. The `-resnik` version is probably good, too, as it gives weight proportional to the number of senses for a word. I'm not sure which performs empirically better, if any does.

>  If not, then perhaps the documentation could default to [...]

Yes, that's probably a good idea.

> Either that or maybe an Exception for the ic.py code which explains why the ValueError was thrown and what can be done about it.

Yeah, maybe best to do both. Not everyone reads the documentation :)

Thanks for the feedback!

**Comment by goodmami** [comment]
@M49ICKPIxi3 it took me a while to get to this but I've now updated the [wn.ic](https://wn.readthedocs.io/en/latest/api/wn.ic.html) documentation so the example shows the file with smoothing and there's a short explanation in the text.

I did not introduce a custom exception on the ValueError because I could no longer recreate the error with the latest version of the software and data, and therefore I couldn't test it out. If some example persists with the newest software and data, I'd probably add in the custom error message. But for now I think the documentation fix is sufficient.
