### ISSUE TITLE
Support WNLMF 1.2 and 1.3

### ISSUE THREAD

**Issue by jmccrae** [goodmami/wn#200]
**Is your feature request related to a problem? Please describe.**
Currently the library rejects wordnets in XML written with the two most recent DTDs:
https://github.com/globalwordnet/schemas/blob/master/WN-LMF-1.2.dtd
https://github.com/globalwordnet/schemas/blob/master/WN-LMF-1.3.dtd

**Additional context**
Mostly this fix just needs to support the new version numbers. There is only one technical change, in that `Pronunciation`, `Tag`, `Definition`, `ILIDefinition` and `Example` now have an optional `xml:space` attribute that should be implemented according to the [XML guidelines](https://www.w3.org/TR/xml/#sec-white-space)

**Comment by goodmami** [comment]
Thanks, I've been meaning to fix this. Seems like a good time with all the other changes going on.

**Comment by goodmami** [comment]
The fix I've settled on for now:

- Allow WN-LMF 1.2 (nothing to do besides allowing the doctype)
- Allow WN-LMF 1.3 on read
  - If `xml:space="preserve"`, do not modify the element's text
  - Otherwise, normalize the element's text's whitespace with `" ".join(elem["text"].split())`

The fact that `xml:space="preserve"` was present on an element is not stored in the database, so the attribute will be lost if one exports the lexicon. This is just a compromise to get WN-LMF 1.3 support out the door without having to figure out the database changes needed.
